### ISSUE TITLE
Include a reference to a free program instead of  "please contact me"

### ISSUE THREAD

**Issue by caprieldeluca** [mammothgeospatial/qgis-in-mineral-exploration#18]
Hi,

I'm the copyright holder of 

> "a small python program that uses 2 common sets of points to calculate a grid origin and rotation amount." <sup>[1]</sup>

The program finds the transformation parameters between two three-dimensional Cartesian systems and is published under MIT license at https://github.com/caprieldeluca/simil.

Furthermore, that piece of code is only a partial implementation of a geometric algebra algorithm, whose author is really the one who deserves merit.

My collaboration in Geoscience plugin was mainly advising on derived-from-projected, through an affine transformation in two dimensions, coordinate reference systems under the WKT:2019 standard. The piece of code, however, is also used in geodetic, robotic and augmented reality applications.

I am currently preparing a presentation precisely on an application of that program, which is about bringing georeferenced point clouds to arbitrary three-dimensional Cartesian systems, using the geocentric system as a pivot. As part of my presentation, a slide shows other applications that also use or used the code.

It is difficult for me to present a code that I have written, to mention a possible geological application, which on a reference page of the discipline is offered in a way that I consider at least unclear:

> "If you would like a copy of this python code, please contact me." <sup>[2]</sup>

I ask, please, if you could remove this last phrase since it is not necessary to contact anyone to get that piece of code, or failing that, place the proper reference.

Regards,
Gabriel

---
[1][2] Grant Boxer, 2024. Retrieved June 18, 2024 from https://qgis-in-mineral-exploration.readthedocs.io/en/latest/source/geological_data/grid_conversion.html

**Comment by johnwbryant** [comment]
Thanks Gabriel, sorry for the delay in responding, appreciate the feedback. I changed it to reference your repo instead.

Happy to review a PR if you like, or feel free to suggest other changes.

Cheers!
John

**Comment by caprieldeluca** [comment]
Hi John, thanks, and congratulations on the manual. 
Although it is not my area of ​​work, I have been reading it and found it to be very complete.

Regards,
Gabriel
